FROM wordpress:5.6-php7.4-apache

# Use the development config
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

# Copy extra configs/overrides
COPY ./conf/php /tmp/conf
RUN mv /tmp/conf/* "$PHP_INI_DIR/conf.d"
