
name: Deploy to Sandbox

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Trigger Remote Deploy Script
        run: |
          curl -X POST -d "site_name=tttttt" -d "repo_url=${{ github.repository_url }}" -d http://sandbox.awp.sh/deploy.sh
